server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  otlp:
    metrics:
      export:
        enabled: true
        url: http://otel-collector:4318/v1/metrics

spring:
  application:
    name: flashdeal-app
  data:
    mongodb:
      uri: mongodb://mongo:27017/flashdeal
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
  file:
    name: /var/log/flashdeal/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB