services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashdeal-dev
    volumes:
      - ..:/workspaces/flashdeal:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - logs-data:/var/log/flashdeal
      - flashdeal-gradle-cache:/home/vscode/.gradle
      - flashdeal-node-modules:/workspaces/flashdeal/src/frontend/node_modules
    command: sleep infinity
    networks:
      - flashnet
      
  mongo:
    image: mongo:6
    container_name: flashdeal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flashnet

  redis:
    image: redis:7-alpine
    container_name: flashdeal-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - flashnet

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: flashdeal-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - flashnet

  kafka:
    image: redpandadata/redpanda:latest
    container_name: flashdeal-kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "1"
      - --check=false
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - flashnet

  loki:
    image: grafana/loki:2.9.4
    container_name: flashdeal-loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    networks:
      - flashnet

  promtail:
    image: grafana/promtail:2.9.4
    container_name: flashdeal-promtail
    volumes:
      - logs-data:/var/log/flashdeal:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/promtail-config.yaml:/etc/promtail/promtail-config.yml:ro
    command: ["-config.file=/etc/promtail/promtail-config.yml"]
    networks: 
      - flashnet

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    container_name: flashdeal-otel
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - flashnet

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: flashdeal-prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - flashnet

  grafana:
    image: grafana/grafana:11.1.4
    container_name: flashdeal-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - flashnet

  k6:
    image: grafana/k6:0.49.0
    container_name: flashdeal-k6
    entrypoint: []
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ../k6:/k6
    networks:
      - flashnet

networks:
  flashnet:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  grafana-data:
  flashdeal-gradle-cache:
  flashdeal-node-modules:
  logs-data: